# Regenerates CMakePresets.json from the axis lists in cmake/SturdyMatrix.cmake, declaring one
# configure preset and one Runtime build preset for every Arch x OS x Profile combination.
#
#   cmake -P cmake/GeneratePresets.cmake
#
# Preset names are "<arch>-<os>-<profile>", all lowercase (e.g. x86-64-linux-debug,
# arm64-win-relwithdebinfo). Do not edit CMakePresets.json by hand — change the lists (or this
# generator) and re-run. Personal tweaks belong in CMakeUserPresets.json, which CMake overlays
# automatically and which stays untracked.
cmake_minimum_required(VERSION 3.28)

include("${CMAKE_CURRENT_LIST_DIR}/SturdyMatrix.cmake")

get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(_configure_presets "")
set(_build_presets "")

foreach(_arch IN LISTS STURDY_ARCH_LIST)
    foreach(_os IN LISTS STURDY_OS_LIST)
        foreach(_profile IN LISTS STURDY_PROFILE_LIST)
            sturdy_preset_name("${_arch}" "${_os}" "${_profile}" _name)
            sturdy_binary_dir("${_arch}" "${_os}" "${_profile}" _binary_dir)

            string(APPEND _configure_presets "    {
      \"name\": \"${_name}\",
      \"displayName\": \"${_arch} ${_os} ${_profile}\",
      \"inherits\": \"base\",
      \"binaryDir\": \"\${sourceDir}/${_binary_dir}\",
      \"cacheVariables\": {
        \"CMAKE_BUILD_TYPE\": \"${_profile}\",
        \"STURDY_ARCH\": \"${_arch}\",
        \"STURDY_OS\": \"${_os}\"
      }
    },\n")

            string(APPEND _build_presets "    {
      \"name\": \"runtime-${_name}\",
      \"displayName\": \"Runtime ${_arch} ${_os} ${_profile}\",
      \"configurePreset\": \"${_name}\",
      \"targets\": [\"Runtime\"]
    },\n")
        endforeach()
    endforeach()
endforeach()

# Trim the trailing ",\n" from the last entry of each array.
string(REGEX REPLACE ",\n$" "\n" _configure_presets "${_configure_presets}")
string(REGEX REPLACE ",\n$" "\n" _build_presets "${_build_presets}")

set(_json "{
  \"version\": 6,
  \"vendor\": {
    \"sturdyengine.dev/generated\": \"Generated by cmake/GeneratePresets.cmake from the axis lists in cmake/SturdyMatrix.cmake. Do not edit by hand; re-run: cmake -P cmake/GeneratePresets.cmake\"
  },
  \"configurePresets\": [
    {
      \"name\": \"base\",
      \"displayName\": \"Base (Ninja + clang pin, compile_commands.json export)\",
      \"hidden\": true,
      \"generator\": \"Ninja\",
      \"cacheVariables\": {
        \"CMAKE_C_COMPILER\": \"clang\",
        \"CMAKE_CXX_COMPILER\": \"clang++\",
        \"CMAKE_EXPORT_COMPILE_COMMANDS\": \"ON\"
      }
    },
${_configure_presets}  ],
  \"buildPresets\": [
${_build_presets}  ]
}
")

file(WRITE "${_root}/CMakePresets.json" "${_json}")

list(LENGTH STURDY_ARCH_LIST _arch_count)
list(LENGTH STURDY_OS_LIST _os_count)
list(LENGTH STURDY_PROFILE_LIST _profile_count)
math(EXPR _combo_count "${_arch_count} * ${_os_count} * ${_profile_count}")
message(STATUS "Wrote ${_root}/CMakePresets.json: ${_combo_count} configure presets + ${_combo_count} build presets")
