include_guard(GLOBAL)

# Directory this engine ships its own Slang shader source under (matches EngineConfig::
# shaders_directory's own "Shaders" default). Every *.slang file directly inside it (flat, no
# subdirectories -- matches how discover_shaders()/ShaderWatcher already assume a flat tree keyed by
# file stem) gets #embed-ed into the binary at configure time, so a shipped build works with no
# Shaders/ folder sitting next to the executable at all -- see Core/Slang/
# EmbeddedShaders.hpp's own doc comment for exactly which code paths fall back to this table and when.
set(STURDY_SHADERS_DIR "${CMAKE_SOURCE_DIR}/Shaders" CACHE PATH
    "Directory of engine-shipped .slang shader sources to embed into the binary at compile time."
)

# Generates the Core::Slang::embedded_shaders()/find_embedded_shader() implementation. Mirrors
# sturdy_generate_license_embeds() in cmake/SturdyLicenses.cmake closely enough to reuse its
# sturdy_check_embed_support()/sturdy_file_to_hex_literal() helpers directly -- SturdyLicenses.cmake
# must be include()d before this function is called (see root CMakeLists.txt's include order).
# Runs at configure time; the glob uses CONFIGURE_DEPENDS under the same STURDY_GLOB_CONFIGURE_DEPENDS
# option sturdy_add_package's own source globbing uses, so adding/removing a .slang file triggers a
# reconfigure automatically rather than needing a manual `cmake .` before the new/removed file is
# reflected in the embedded table.
function(sturdy_generate_shader_embeds)
    sturdy_check_embed_support()

    set(_sturdy_glob_options)
    if(STURDY_GLOB_CONFIGURE_DEPENDS)
        list(APPEND _sturdy_glob_options CONFIGURE_DEPENDS)
    endif()

    file(GLOB _sturdy_shader_files ${_sturdy_glob_options} "${STURDY_SHADERS_DIR}/*.slang")
    list(SORT _sturdy_shader_files)

    set(_sturdy_byte_arrays "")
    set(_sturdy_table_entries "")

    foreach(_sturdy_shader_file IN LISTS _sturdy_shader_files)
        get_filename_component(_sturdy_shader_name "${_sturdy_shader_file}" NAME)
        get_filename_component(_sturdy_shader_stem "${_sturdy_shader_file}" NAME_WE)
        string(MAKE_C_IDENTIFIER "${_sturdy_shader_stem}" _sturdy_ident)

        if(STURDY_HAVE_CXX_EMBED)
            set(_sturdy_bytes_body "#embed \"${_sturdy_shader_file}\" if_empty(0)")
        else()
            sturdy_file_to_hex_literal("${_sturdy_shader_file}" _sturdy_bytes_body)
        endif()

        # unsigned char (not char), const (not constexpr) -- same reasoning as
        # sturdy_generate_license_embeds()'s own byte arrays; see that function's comment.
        string(APPEND _sturdy_byte_arrays
            "        inline const unsigned char ${_sturdy_ident}_shader_bytes[] = {\n${_sturdy_bytes_body}\n        };\n\n"
        )
        string(APPEND _sturdy_table_entries
            "            {\"${_sturdy_shader_name}\", \"${_sturdy_shader_stem}\", Foundation::EmbeddedText{reinterpret_cast<const char *>(${_sturdy_ident}_shader_bytes), sizeof(${_sturdy_ident}_shader_bytes)}},\n"
        )
    endforeach()

    set(_sturdy_generated_file "${CMAKE_BINARY_DIR}/generated/Core/EmbeddedShadersEmbed.cpp")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated/Core")
    file(WRITE "${_sturdy_generated_file}" "\
// GENERATED by cmake/SturdyShaders.cmake (sturdy_generate_shader_embeds) at configure time, from
// every *.slang file under ${STURDY_SHADERS_DIR}. Do not hand-edit -- re-run cmake to regenerate.
#if defined(__clang__)
#pragma clang diagnostic ignored \"-Wc23-extensions\"
#endif
#include <span>
#include <string_view>
#include <Foundation/Foundation.hpp>

#include <Core/Slang/EmbeddedShaders.hpp>

namespace SFT::Core::Slang {
    namespace {
${_sturdy_byte_arrays}        inline const EmbeddedShaderSource all_embedded_shaders_table[] = {
${_sturdy_table_entries}        };
    } // namespace

    std::span<const EmbeddedShaderSource> embedded_shaders() noexcept {
        return all_embedded_shaders_table;
    }

    const EmbeddedShaderSource *find_embedded_shader(std::string_view path_or_module_name) noexcept {
        // Filename-only match (see this function's own header doc comment for why): strip any
        // directory components from the query so a search-path-combined path (e.g.
        // \"Shaders/sturdy_common.slang\") still matches the bare \"sturdy_common.slang\" key.
        const std::string_view::size_type slash = path_or_module_name.find_last_of(\"/\\\\\");
        const std::string_view filename =
            slash == std::string_view::npos ? path_or_module_name : path_or_module_name.substr(slash + 1);

        for (const EmbeddedShaderSource &entry : all_embedded_shaders_table) {
            if (entry.relative_path == filename || entry.relative_path == path_or_module_name ||
                entry.module_name == path_or_module_name) {
                return &entry;
            }
        }
        return nullptr;
    }
} // namespace SFT::Core::Slang
")

    set(STURDY_SHADERS_EMBED_CPP "${_sturdy_generated_file}" CACHE INTERNAL
        "Generated Core::Slang::embedded_shaders() implementation embedding every engine-shipped .slang file."
    )
endfunction()
