include_guard(GLOBAL)

# The debug text overlay (Renderer/src/Renderer/RendererTextOverlay.cpp) finds a system font by
# scanning real filesystem directories (Text::FontDatabase::create over "Fonts" plus each
# platform's font_search_directories()). That has nothing to scan on Web -- Emscripten has no real
# filesystem and Text/Platform/Web/FontsImpl.cpp's font_search_directories() correctly returns
# empty rather than pretending otherwise -- so the overlay could never build there. Embedding one
# fallback font mirrors sturdy_generate_shader_embeds() in SturdyShaders.cmake exactly: same
# #embed-if-available/hex-literal-fallback split, same "prefer real dependency, fall back to the
# embedded copy" shape already used for shaders and licenses.
set(STURDY_DEFAULT_FONT_FILE "${CMAKE_SOURCE_DIR}/Fonts/MapleMono-NF-Regular.ttf" CACHE PATH
    "Font file embedded into the binary as the debug text overlay's last-resort fallback."
)

# Generates the Renderer::Text::embedded_default_font()/embedded_default_font_bytes() implementation.
# Reuses sturdy_check_embed_support()/sturdy_file_to_hex_literal() from SturdyLicenses.cmake, which
# must be include()d before this function is called (see root CMakeLists.txt's include order).
function(sturdy_generate_font_embeds)
    sturdy_check_embed_support()

    if(NOT EXISTS "${STURDY_DEFAULT_FONT_FILE}")
        message(FATAL_ERROR "STURDY_DEFAULT_FONT_FILE does not exist: ${STURDY_DEFAULT_FONT_FILE}")
    endif()

    if(STURDY_HAVE_CXX_EMBED)
        set(_sturdy_font_bytes_body "#embed \"${STURDY_DEFAULT_FONT_FILE}\" if_empty(0)")
    else()
        sturdy_file_to_hex_literal("${STURDY_DEFAULT_FONT_FILE}" _sturdy_font_bytes_body)
    endif()

    set(_sturdy_generated_file "${CMAKE_BINARY_DIR}/generated/Renderer/EmbeddedFontEmbed.cpp")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated/Renderer")
    file(WRITE "${_sturdy_generated_file}" "\
// GENERATED by cmake/SturdyFonts.cmake (sturdy_generate_font_embeds) at configure time, from
// ${STURDY_DEFAULT_FONT_FILE}. Do not hand-edit -- re-run cmake to regenerate.
#if defined(__clang__)
#pragma clang diagnostic ignored \"-Wc23-extensions\"
#endif
#include <cstddef>
#include <span>

#include <Renderer/Text/EmbeddedFont.hpp>

namespace SFT::Text {
    namespace {
        inline const unsigned char default_font_bytes[] = {
${_sturdy_font_bytes_body}
        };
    } // namespace

    std::span<const std::byte> embedded_default_font_bytes() noexcept {
        return std::span<const std::byte>{
            reinterpret_cast<const std::byte *>(default_font_bytes), sizeof(default_font_bytes)};
    }
} // namespace SFT::Text
")

    set(STURDY_FONTS_EMBED_CPP "${_sturdy_generated_file}" CACHE INTERNAL
        "Generated Renderer::Text::embedded_default_font_bytes() implementation embedding the fallback debug-overlay font."
    )
endfunction()
